### ISSUE TITLE
Need to verify the full name of the method.

### ISSUE THREAD

**Issue by anton-sergeev** [fraxer/elekard#2]
Here is a method name check based on only the first two characters. This is a deviation from the standard.

https://github.com/fraxer/elekard/blob/815ec872c8aa285e955a1c9233cf412cd3fe149d/src/server.cpp#L228

**Comment by fraxer** [comment]
Сorrected here https://github.com/fraxer/http-https-epoll-server/blob/0d9991ea4a5fff9975fadd29888be0dabe9bdcdc/src/functions/functions.cpp#L387
